apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: amjad
  labels: 
    name: amjad
spec:
  type: NodePort
  selector:
    app: tawazun
    service: tawazun-svc
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080
      nodePort: 32000



